site_name: Annie Documentation
nav:
  - Home: index.md
  - API Reference:
    - AnnIndex: api/ann_index.md
    - PyHnswIndex: api/hnsw_index.md
    - ThreadSafeAnnIndex: api/threadsafe_index.md
  - Features:
    - Concurrency: concurrency.md
    - Filtered Search: filtering.md
  - Examples: examples.md

theme: readthedocs
markdown_extensions:
  - toc:
      permalink: true