  first-interaction:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest
    steps:
      - name: First interaction
        uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            👋 Welcome, and thanks for opening your first issue!  
            We appreciate your contribution. Our maintainers will review it soon.
          pr-message: >
            🎉 Thank you for your first pull request!  
            A maintainer will review it and provide feedback as soon as possible.
